version: 2.1

orbs:
  node: circleci/node@5.2.0
  browser-tools: circleci/browser-tools@1.4.8

jobs:
  test-unit:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run unit tests
          command: npm test
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: coverage

  test-e2e:
    executor: 
      name: node/default
      tag: '18.17'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          name: Install Playwright browsers
          command: npx playwright install chromium
      - run:
          name: Start development server
          command: npm run dev
          background: true
      - run:
          name: Wait for server to start
          command: npx wait-on http://localhost:3000
      - run:
          name: Run E2E tests
          command: npm run test:e2e
      - store_test_results:
          path: playwright-report
      - store_artifacts:
          path: playwright-report

  lint:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run linting
          command: npm run lint

  build:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Build application
          command: npm run build
      - store_artifacts:
          path: .next

workflows:
  test-and-build:
    jobs:
      - test-unit
      - lint
      - build
      - test-e2e:
          requires:
            - test-unit
            - lint